
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
