version: "3"

services:
  mysql:
    image: mysql:8.0
    volumes: /tmp:/tmp
    networks:
      - network
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "philz"
    restart: always
  philz:
    image: philz-customer
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 8080
    environment:
      - MYSQL_HOST: "mysql"
    restart: always
  lb:
    image: eeacms/haproxy
    depends_on:
      - philz
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "philz"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "true"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge
