apiVersion: v1
kind: Service
metadata:
  name: philz-customer-service 
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080 
  selector:
    name: philz-customer