apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: philz-cart
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /rest
        backend:
          serviceName: philz-cart
          servicePort: 81
