package com.example.philzapidb.enums.order;

public enum DrinkType {
    JACOBS, ETHER, ARABIC, TURKISH, TESORA, PHILHARMONIC, JULIES, SOUL,
    SILKEN, ALARM, GRATITUDE, AMBROSIA, DANCINGWATER, NEWMANHATTAN, MOCHA, WINTER,
    COLUMBIADECAF, MEDIUMDECAF, LIGHTDECAF, ECSTATIC, MOJITO, ROSE, GINGERSNAP,
    MISSIONCOLDBREW, SOULCOLDBREW
}
